on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Send release to Telegram channel
        run: curl -F chat_id=1770660386 -F parse_mode=Markdown -F text=steps.getRelease.outputs.release https://api.telegram.org/bot{config.telegram_token}/sendMessage
        
